version: '3'
services:
    backend:
        container_name: backend
        environment:
            - DATABASE_URL=mongodb://mongo/miaAjudaDB
        build:
            context: .
            dockerfile: Dockerfile
        command: "yarn start"
        ports:
            - "8000:8000"
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo 
            