version: '3'
services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        command: "yarn start"
        ports:
            - "8000:8000"
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"