openapi: 3.0.0
info:
  version: v1
  title: API MiaAjuda
  description: API MiaAjuda
  termsOfService: None
  contact:
    name: Mia Ajuda
    url: https://github.com/mia-ajuda
servers:
  - url: http://localhost:8000/api
paths:
  /user:
    post:
      tags:
        - User
      operationId: postUser
      description: Rota de criação de usuário
      parameters:
        - name: hasUser
          in: query
          required: false
          description: Parâmetro que indica se o usuário possui ou não um usuário. Só deve ser usado quando a conta for criada usando o Facebook ou gmail, onde o hasUser deve ser true
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
    put:
      security:
        - bearerAuth: []
      tags:
        - User
      operationId: putUser
      description: Rota de edição de usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '401':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '403':
          description: Usuário não está autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '404':
          description: Aplicação não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
    delete:
      security:
        - bearerAuth: []
      tags:
        - User
      operationId: deleteUser
      description: Rota de deleção lógica de usuário
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '401':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '403':
          description: Usuário não está autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '404':
          description: Aplicação não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
  '/user/adress':
    put:
      security:
        - bearerAuth: []
      tags:
        - User
      operationId: putUserAdress
      description: Rota de edição de endereço do usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserAdressRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '401':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '403':
          description: Usuário não está autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '404':
          description: Aplicação não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
  '/user/location':
    put:
      security:
        - bearerAuth: []
      tags:
        - User
      operationId: putUserLocation
      description: Rota de edição de localização do usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserLocationRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '401':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '403':
          description: Usuário não está autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '404':
          description: Aplicação não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
  /user/getUser/{userId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User
      operationId: GetUserByIdOrToken
      description: Rota para obter detalhes de um usuário por id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
        '401':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '403':
          description: Usuário não está autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
        '404':
          description: Aplicação não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
  /groupRisk:  
    get:
      tags:
        - User
      operationId: getGroupRisk
      description: Rota de obtenção da lista de grupos de risco
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupRiskResponse'
  /checkUserExistence/{value}:  
    get:
      tags:
        - User
      operationId: checkUserExistence
      description: Rota de verificação de existência de um usuário
      parameters:
        - name: value
          in: path
          required: true
          schema:
            type: string
            description: Um email ou cpf do usuário.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/checkUserExistenceResponse'
                
  /category:
    get:
      tags:
        - Category
      operationId: GetAllCategory
      description: Rota para obter as categorias dos pedidos de ajuda
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
  /category/{id}:
    get:
      tags:
        - Category
      operationId: GetCategoryById
      description: Rota para obter detalhes de uma categoria
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsResponse'
components:
  schemas:
    
    ############### User ################
    
    PostUserRequest:
      type: object
      properties:
        groupRisc:
          type: array
          items: 
            type: string
        name: 
          type: string
        email: 
          type: string
        birthday:
          type: string
          format: date
        cpf: 
          type: string
        photo: 
          type: string
        address:
          type: object
          properties:
            cep: 
              type: string
            number: 
              type: number
            city: 
              type: string
            state: 
              type: string
            complement: 
              type: string
        password: 
          type: string
          minLength: 8
        latitude: 
          type: number
        longitude: 
          type: number
        phone: 
          type: string
          minLength: 9
      required: 
        - name
        - email
        - cpf
        - password
    
    PutUserRequest:
      type: object
      properties:
        photo: 
          type: string
        name: 
          type: string
        notificationToken: 
          type: string
        deviceId:
          type: string
          
    PutUserLocationRequest:
      type: object
      properties:
        latutide: 
          type: number
        longitude: 
          type: number
    
    PutUserAdressRequest:
      type: object
      properties:
        cep: 
          type: string
        number: 
          type: string
        city: 
          type: string
        state: 
          type: string
        complement:
          type: string
          
    PostUserResponse:
      type: object
      properties:
        ismentalHealthProfessional: 
          type: boolean
        active: 
          type: boolean
        _id: 
          type: string
        location: 
          type: object
          properties:
            coordinates: 
              type: array
              items:
                type: number
            id:
              type: string
            type:
              type: string
              default: Point
        groupRisc:
          type: array
          items: 
            type: string
        name: 
          type: string
        email: 
          type: string
        birthday:
          type: string
          format: date
        cpf: 
          type: string
        photo: 
          type: string
        address:
          type: object
          properties:
            cep: 
              type: string
            number: 
              type: number
            city: 
              type: string
            state: 
              type: string
            complement: 
              type: string
        password: 
          type: string
        latitude: 
          type: number
        longitude: 
          type: number
        phone: 
          type: string
    
    GroupRiskResponse:
      type: object
      properties:
        dc:
          type: string
          default: Doença respiratória
          description: Doença respiratória
        hiv: 
          type: string
          default: HIV
          description: HIV
        diab: 
          type: string
          default: Diabetes
          description: Diabetes
        hiperT: 
          type: string
          default: Hipertensão
          description: Hipertensão
        doenCardio: 
          type: string
          default: Doenças cardiovasculares
          description: Doenças cardiovasculares
          
    checkUserExistenceResponse:
      type: boolean
        
    
    ############# End User ##############

    ########## Start Category ###########

    CategoryResponse:
      type: object
      properties:
        _id:
          type: string
        active:
          type: boolean
        name:
          type: string
        description:
          type: string
   
    ########### End Category ###########
    
    ############## Misc ################

    ProblemDetailsResponse:
      type: object
      properties:
        error:
          type: string
          
    ############## Misc ################
    
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT   