name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 🏗 Config files
        run:  |
              echo "$FIREBASE_CONFIG" > ./src/config/firebaseAuthConfig.js
              echo "$RCLONE_CONFIG" > ./config/rclone.conf

              
      - name: 📦  Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: 📦  Docker push image
        run:  |
              docker build . -t "$IMAGE_NAME"
              docker push "$IMAGE_NAME"

      - name: 📦  Docker push image tag latest if develop
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        run:  |
              docker tag "$IMAGE_NAME" ${{ secrets.DOCKER_REPOSITORY }}:latest
              docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
